apiVersion: apps/v1
kind: Deployment
metadata:
    name: sensors
    labels:
        app: sensors
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sensors
    template:
        metadata:
            labels:
                app: sensors
        spec:
            containers:
                - name: sensors
                  image: tamas99/sensors-image:amd64-1.6
---
apiVersion: v1
kind: Service
metadata:
    name: sensors
spec:
    type: LoadBalancer
    selector:
        app: sensors
    ports:
        - protocol: TCP
          port: 8010
          targetPort: 8010
