---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  serviceName: kafka
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.11-1.1.0
          ports:
            - containerPort: 9092
          env:
            - name: HOSTNAME_COMMAND
              value: "echo \"$HOSTNAME.kafka\""
            - name: BROKER_ID_COMMAND
              value: "hostname | awk -F'-' '{print $2}'"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-0.zookeeper:22181,\
                      zookeeper-1.zookeeper:22181,\
                      zookeeper-2.zookeeper:22181"
            - name: KAFKA_LISTENERS
              value: "INSIDE://:9092,OUTSIDE://:9094"
            - name: KAFKA_ADVERTISED_LISTENERS
              #value: "INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9092"
              value: "INSIDE://:9092,OUTSIDE://10.10.132.197:9094"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_LOG_DIRS
              value: "/kafka-logs"
            - name: JMX_PORT
              value: "9999"
          # volumeMounts:
          #   - name: logs
          #     mountPath: /kafka-logs
          #     subPath: logs
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
        storageClassName: "nfs-client"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - port: 9094
