apiVersion: apps/v1
kind: Deployment
metadata:
    name: prediction
    labels:
        app: prediction
spec:
    replicas: 1
    selector:
        matchLabels:
            app: prediction
    template:
        metadata:
            labels:
                app: prediction
        spec:
            containers:
                - name: prediction
                  image: tamas99/prediction-image:amd64-1.9
---
apiVersion: v1
kind: Service
metadata:
    name: prediction
spec:
    type: LoadBalancer
    selector:
        app: prediction
    ports:
        - protocol: TCP
          port: 8020
          targetPort: 8020
